name: konsi
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  dio: ^5.7.0
  get_it: ^8.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
 
  
flutter_native_splash:
  color: '#2E8896'
  image: assets/images/android_logo.png
  fullscreen: true

  android_12:
    color: '#2E8896'
    image: assets/images/android_logo.png
    fullscreen: true
  
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

